CREATE DATABASE QuanLyGiaoVu;
USE QuanLyGiaoVu;

CREATE TABLE KHOA
(
	MAKHOA varchar(4) PRIMARY KEY,
	TENKHOA varchar(40),
	NGTLAP smalldatetime,
	TRGKHOA char(4),
);

CREATE TABLE GIAOVIEN
(
	MAGV char(4) PRIMARY KEY,
	HOTEN varchar(40),
	HOCVI varchar(10),
	HOCHAM varchar(10),
	GIOITINH varchar(3),
	NGSINH smalldatetime,
	NGVL smalldatetime,
	HESO numeric(4,2),
	MUCLUONG money,
	MAKHOA varchar(4) FOREIGN KEY REFERENCES KHOA(MAKHOA),
);

CREATE TABLE MONHOC
(
	MAMH varchar(10) PRIMARY KEY,
	TENMH varchar(40),
	TCLT tinyint,
	TCTH tinyint,
	MAKHOA varchar(4) FOREIGN KEY REFERENCES KHOA(MAKHOA),
);

CREATE TABLE LOP
(
	MALOP char(3) PRIMARY KEY,
	TENLOP varchar(40),
	TRGLOP char(5),
	SISO tinyint,
	MAGVCN char(4),
);

CREATE TABLE HOCVIEN
(
	MAHV char(5) PRIMARY KEY,
	HO varchar(40),
	TEN varchar(10),
	NGSINH smalldatetime,
	GIOITINH varchar(3),
	NOISINH varchar(40),
	MALOP char(3) FOREIGN KEY REFERENCES LOP(MALOP),
);

CREATE TABLE GIANGDAY
(
	MALOP char(3) FOREIGN KEY REFERENCES LOP(MALOP),
	MAMH varchar(10) FOREIGN KEY REFERENCES MONHOC(MAMH),
	MAGV char(4) FOREIGN KEY REFERENCES GIAOVIEN(MAGV),
	HOCKY tinyint,
	NAM smallint,
	TUNGAY smalldatetime,
	DENNGAY smalldatetime,
	PRIMARY KEY(MALOP,MAMH)
);

CREATE TABLE DIEUKIEN
(
	MAMH varchar(10),
	MAMH_TRUOC varchar(10),
	PRIMARY KEY(MAMH,MAMH_TRUOC)
);

CREATE TABLE KETQUATHI
(
	MAHV char(5) FOREIGN KEY REFERENCES HOCVIEN(MAHV),
	MAMH varchar(10) FOREIGN KEY REFERENCES MONHOC(MAMH),
	LANTHI tinyint,
	NGTHI smalldatetime,
	DIEM numeric(4,2),
	KQUA varchar(10),
	PRIMARY KEY(MAHV,MAMH,LANTHI),
);

--USE master
--DROP DATEBASE QuanLyGiaoVu

ALTER TABLE KHOA
ADD FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV);

--3
ALTER TABLE HOCVIEN
ADD CONSTRAINT GIOITINH_CONTRAINT CHECK (GIOITINH = 'nam' OR GIOITINH = 'nu');
--4
ALTER TABLE KETQUATHI
ADD CONSTRAINT DIEM_CONTRAINT CHECK (DIEM >=0 AND DIEM <=10);
--5.1
ALTER TABLE KETQUATHI
ADD CONSTRAINT KQ1_CONTRAINT CHECK (((DIEM >= 5 AND DIEM <=10) AND (KQUA = 'Dat')) OR (DIEM < 5 AND KQUA = 'Khong dat'));
--5.2
ALTER TABLE KETQUATHI
ADD CONSTRAINT KQ2_CONTRAINT CHECK ((LANTHI >= 2 AND DIEM > 6 AND KQUA = 'Dat') OR (LANTHI >= 2 AND DIEM <=6 AND KQUA = 'Khong dat') 
OR (LANTHI = 1 AND DIEM >=5 AND DIEM <=10 AND KQUA = 'Dat') OR (LANTHI = 1 AND DIEM <5  AND KQUA = 'Khong dat'));
--6
ALTER TABLE KETQUATHI
ADD CONSTRAINT THI_CONTRAINT CHECK (LANTHI <=3);
--7
ALTER TABLE GIANGDAY
ADD CONSTRAINT GIANGDAY_CONTRAINT CHECK (HOCKY = 1 OR HOCKY = 2 OR HOCKY = 3);
--8
ALTER TABLE GIAOVIEN
ADD CONSTRAINT GIAOVIEN_CONTRAINT CHECK (HOCVI = 'CN' OR HOCVI = 'KS' OR HOCVI = 'Ths' OR HOCVI = 'TS' OR HOCVI = 'PTS');

--USE master;
--DROP DATABASE QuanLyGiaoVu;